FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm i

# Copy the rest of the application
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the application using the production build
CMD ["npm", "run", "dev"]
