version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://love.valentine2dot0.me/api
      - NEXT_PUBLIC_MINIO_URL=https://love.valentine2dot0.me:443
      - NEXT_PUBLIC_SPOTIFY_CLIENT_ID=27d40b1175aa4158af7446c0fc085f71
      - NEXT_PUBLIC_SPOTIFY_REDIRECT_URI=https://love.valentine2dot0.me/callback
    depends_on:
      - backend
    networks:
      bridge:
        ipv4_address: 192.168.50.3
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGO_URI=mongodb+srv://louderdev:123@cluster0.bqke2cc.mongodb.net?authSource=admin
      # MinIO Configuration
      - MINIO_INTERNAL_ENDPOINT=minio
      - MINIO_PORT=443
      - MINIO_USE_SSL=true
      - MINIO_BUCKET_NAME=sit-valentine1
      - MINIO_PUBLIC_ENDPOINT=https://minio.bsthun.com
      - MINIO_ACCESS_KEY=Q0cEpIA853SRR886IG7r
      - MINIO_SECRET_KEY=9WablMiukRpIEJLVD8ARLl3GI1rsAOsysGSc1NHv
      # Spotify Configuration
      - SPOTIFY_CLIENT_ID=27d40b1175aa4158af7446c0fc085f71
      - SPOTIFY_CLIENT_SECRET=27a205ea8f9e4cdcb59add7ab190d6f0
      - SPOTIFY_REDIRECT_URI=https://love.valentine2dot0.me/callback
    depends_on:
      - mongo
    networks:
      bridge:
        ipv4_address: 192.168.50.2

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=louderdev
      - MONGO_INITDB_ROOT_PASSWORD=123
    networks:
      bridge:
        ipv4_address: 192.168.50.1
    volumes:
      - mongo-data:/data/db

  # Uncomment MinIO if needed
  # minio:
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - minio-data:/data
  #   environment:
  #     - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
  #     - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
  #     # CORS Configuration
  #     - MINIO_CORS_ALLOW_ORIGINS=*
  #     - MINIO_CORS_ALLOW_METHODS=GET,PUT,POST,DELETE,OPTIONS
  #     - MINIO_CORS_ALLOW_HEADERS=Accept,Authorization,Content-Type,Content-Length,X-Amz-Date,X-Amz-Security-Token,X-Amz-User-Agent
  #     - MINIO_CORS_EXPOSE_HEADERS=ETag
  #     - MINIO_CORS_MAX_AGE_SECONDS=3600
  #   command: server --console-address ":9001" /data
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   networks:
  #     - app-network

volumes:
  mongo-data:
  minio-data:

networks:
  bridge:
    name: br0
    external: true
