version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_MINIO_URL=http://localhost:9000
      - NEXT_PUBLIC_SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - NEXT_PUBLIC_SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URI=${MONGO_URI}
      # MinIO Configuration
      - MINIO_INTERNAL_ENDPOINT=${MINIO_INTERNAL_ENDPOINT}
      - MINIO_PUBLIC_ENDPOINT=${MINIO_PUBLIC_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      # Spotify Configuration
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    depends_on:
      - minio
    networks:
      - app-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      # CORS Configuration
      - MINIO_CORS_ALLOW_ORIGINS=*
      - MINIO_CORS_ALLOW_METHODS=GET,PUT,POST,DELETE,OPTIONS
      - MINIO_CORS_ALLOW_HEADERS=Accept,Authorization,Content-Type,Content-Length,X-Amz-Date,X-Amz-Security-Token,X-Amz-User-Agent
      - MINIO_CORS_EXPOSE_HEADERS=ETag
      - MINIO_CORS_MAX_AGE_SECONDS=3600
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

volumes:
  minio-data:

networks:
  app-network:
    driver: bridge